# Font
font_size 12
show_hyperlink_targets ctrl


# Clipboard
strip_trailing_spaces smart


# Theme
active_border_color #8000ff
inactive_border_color #808080
hide_window_decorations titlebar-only
foreground #dddddd
background #202020
